### ISSUE TITLE
Potential infinite loop

### ISSUE THREAD

**Issue by sp3c1** [nodkz/mongoose-plugin-autoinc#13]
I know it theoretically should not happen, but  lets adhere to Murphy's Law ;]

https://github.com/nodkz/mongoose-plugin-autoinc/blob/f4807c9a7016221277eb5d70e2185a01eb84cc35/src/index.js#L201

**Comment by sp3c1** [comment]
Also we should in second call avoid creating again the counter as by all means it should be there already

**Comment by nodkz** [comment]
We can split somehow `preSave` on several methods and avoid this problem.

Do you have thoughts how it can be done?

**Comment by sp3c1** [comment]
`preSave(IC, settings, doc, next, attempt = 0)` and then only i attempt is 0 we run`createCounterIfNotExist` increment it in the catch section to set amount of times (2-3) and we should be good. 

Means we wont need to track values, and everything should wrap up nicely in closures.

So that first call stays as it is. and then the timeout runs with `++attempt`

**Comment by nodkz** [comment]
Ok, let's do in such way. 
Do you open PR?

**Comment by sp3c1** [comment]
not yet, will do later this week ^^

**Comment by sp3c1** [comment]
PR #16
