### ISSUE TITLE
Fix babel-runtime

### ISSUE THREAD

**Issue by arso1er** [nodkz/mongoose-plugin-autoinc#2]
Hi, mongoose-plugin-autoinc works great on create. However, when I try to update using findOneAndUpdate from mongoose, it creates another entry in the database, with incremented _id. But what I want is just update the existing entry without incrementing the _id field; it should increment only on document.create.
How can I achieve this?

By the way, I had to install babel-runtime because mongoose-plugin-autoinc didn't do it automatically.

**Comment by arso1er** [comment]
My bad. I made a silly mistake on the front end.

**Comment by nodkz** [comment]
Thanks for reporting. Reopen it due babel-runtime problem.

**Comment by nodkz** [comment]
Fixed in 1.1.3, was removed the dependency from `babel-runtime`
