### ISSUE TITLE
nextCount not work

### ISSUE THREAD

**Issue by iamnotstone** [nodkz/mongoose-plugin-autoinc#21]
I am using mongoose 5.0.6
below is my code:
```
var mongoose = require('mongoose')
  
mongoose.connect('mongodb://localhost/test')
var autoIncrement = require('mongoose-plugin-autoinc')
  
const MySchema = new mongoose.Schema({
  name: { type: String },
  fruitId: Number
})
    
MySchema.plugin(autoIncrement.plugin, {
  model: 'fruit',
  field: 'fruitId'
})

const MyModel = mongoose.model('Fruit', MySchema)
     
var a = new MyModel({
  name: 'stone',
})

a.save(function(err, model){
  if(err) console.log('Error:',err)
  else {
    console.log( 'nextCount', a.nextCount)
    a.nextCount(function(err, count){
      console.log('count:', count)
    })
  }
})
```

The count number never displayed. It seems nextCount don't accept a function as a argument.
console.log('nextCount', a.nextCount) shows below:
nextCount: function (groupingFieldValue) {
    const doc = this;
    const IC = getIC(doc.collection.conn);
    return nextCount(IC, settings, groupingFieldValue);
  }

**Comment by nodkz** [comment]
`nextCount` method returns `Promise`. It does not accept callback.

You should use it in following way https://github.com/nodkz/mongoose-plugin-autoinc/blob/adf49767c5a559c86a9eadb3207e037d915257a0/src/__tests__/github/21-test.js#L46-L49

**Comment by iamnotstone** [comment]
Thank you for the committing . I think you should also update the document here:

> Want to know the next number coming up?
> const Book = connection.model('Book', BookSchema);
> Book.nextCount((err, count) => {
> 
>     // count === 0 -> true
> 
>     const book = new Book();
>     book.save(err1 => {
> 
>         // book._id === 0 -> true
> 
>         book.nextCount((err2, count) => {
> 
>             // count === 1 -> true
> 
>         });
>     });
> });

**Comment by nodkz** [comment]
Thanks a lot!
