### ISSUE TITLE
Autoinc field within a group of documents

### ISSUE THREAD

**Issue by AlexanderButyaev** [nodkz/mongoose-plugin-autoinc#24]
I found this plugin very useful for autoinc of the field within a whole collection. However, I'm curious about its application within some group of documents of a collection. Simple example - I have the following collection (just an example):

```
var Transaction = new Scheme({
  project_id: {type: Number},
  description: {type: String},
  transaction_entry_number: {type: Number}, // <<< to be autoinc given project_id
  ...
)}
```

Then I would like to insert three different documents - two docs for the project "1", and one - for the project "2".
What I want to see for project "1" having two entries with transaction_entry_number = 1 and transaction_entry_number = 2. And for project "2" - transaction_entry_number = 1.

So is there any way to do so with this plugin?

Thanks!

**Comment by AlexanderButyaev** [comment]
Ok, I've checked the source code. Seems that I need groupingField ("The field by which to group documents, allowing for each grouping to be incremented separately."). Please add this to the readme! Hopefully, it's not deprecated or going to be...

**Comment by nodkz** [comment]
Yep, this is correct.
Please add a note about this to README.md
Thanks.
