### ISSUE TITLE
Clustering & Concurrent Requests

### ISSUE THREAD

**Issue by alexpchin** [nodkz/mongoose-plugin-autoinc#4]
I'm pretty sure the answer is no but presumably, this will become unreliable when using clustering or when receiving multiple concurrent requests? If not, are you able to say why? I think this is a hot topic of autoincrement plugins and it would be nice to have a solid answer at the top of the README? 

An example: https://stackoverflow.com/questions/28357965/mongoose-auto-increment

**Comment by nodkz** [comment]
I did not make tests with clustering but sure that it should work without any problems, cause internally used atomic mongodb operation for updating the counter:
https://github.com/nodkz/mongoose-plugin-autoinc/blob/master/src/index.js#L144-L160

With serial record writing from one process, you will get huge performance degradation when using autoincrements. But in many-process apps it will not block operations from each other and can be horizontally scaled.

**Comment by sp3c1** [comment]
I might be wrong, but that not guarantees Atomic only on increment? Which means on retrieval it could possibly collide. If the index is unique that is fine cause data layer would stop such operation but extra logic needs to be put in place to retry and stuff and thats just pain.

If so why not actually return count in the update resolving promise? - that for sure would actually provide safe atomic increment?

**Comment by sp3c1** [comment]
and i think even then its also not really 100% atomic,  as if the db goes down before persisting to drive only in memory, then i guess the value could rollback to some previous state. But thats mongo feature I guess :)

**Comment by nodkz** [comment]
Anyway `schema.index({ [your_counter_field_name]: 1 }, { unique: true });` will guarantee that your autoincrement field is correct on any problems with mongodb. If some problem with DB, you will not able to add a new record with a duplicate id.

**Comment by sp3c1** [comment]
yeah, i know, but if there is a chance to not be redoing request commercially or show random errors to customers - hey sorry its duplicate jest retry, it should be taken ;]

**Comment by sp3c1** [comment]
I think with the latest changes that can be closed now

**Comment by nodkz** [comment]
Yep, thanks a lot @sp3c1
